name: share_plus_web
description: Web platform implementation of share_plus
homepage: https://plus.fluttercommunity.dev/
repository: https://github.com/fluttercommunity/plus_plugins/tree/main/packages/
version: 2.0.4

flutter:
  plugin:
    platforms:
      web:
        pluginClass: SharePlusPlugin
        fileName: share_plus_web.dart

dependencies:
  share_plus_platform_interface: ^2.0.0
  url_launcher: ^6.0.1
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"
